---
abstract: 'introspect overloaded operators'
author:
  - 'Dagfinn Ilmari Mannsåker <ilmari@ilmari.org>'
build_requires:
  Test::More: 0.88
  parent: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.014, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-OverloadInfo
requires:
  Exporter: 0
  MRO::Compat: 0
  Package::Stash: 0
  Scalar::Util: 0
  Sub::Identify: 0
  overload: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Devel-OverloadInfo
  repository: git://github.com/ilmari/Devel-OverloadInfo.git
version: 0.001
